server:
  port: 8080

spring:
#  config:
#      import: optional:file:.env[.properties]
  security:
    user:
      name: ${name}
      password: ${pin}
  data:
    mongodb:
      uri: ${MONGO_URL} 
      database: event-management
  mail:
    host: smtp.gmail.com
    port: 587
    username: abdulwasimsguvi@gmail.com
    password: sznlqabfcbernkph
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
      
razorpay:
  key: ${key}
  secret: ${key_secret}

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 86400000


links:
  url: ${app_url}
  

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# Optional: profiles (e.g., dev, prod)
# spring:
#   profiles:
#     active: dev

